[package]
name = "rust_gem_sample"
version = "0.1.0"
edition = "2021"
authors = ["atolix <82761106+atolix@users.noreply.github.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
